// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountAddress: typeof import('./src/@core/components/account/AccountAddress.vue')['default']
    AccountCard: typeof import('./src/@core/components/account/AccountCard.vue')['default']
    AccountEnablePassword: typeof import('./src/@core/components/account/AccountEnablePassword.vue')['default']
    AccountUpgradePlan: typeof import('./src/@core/components/account/AccountUpgradePlan.vue')['default']
    AppBarSearch: typeof import('./src/@core/components/AppBarSearch.vue')['default']
    AppBarSearchReseller: typeof import('./src/@core/components/AppBarSearchReseller.vue')['default']
    AppCardActions: typeof import('./src/@core/components/AppCardActions.vue')['default']
    AppDateTimePicker: typeof import('./src/@core/components/AppDateTimePicker.vue')['default']
    AppOtpInput: typeof import('./src/@core/components/settings/AppOtpInput.vue')['default']
    AppSearchHeader: typeof import('./src/@core/components/AppSearchHeader.vue')['default']
    CardAddEditDialog: typeof import('./src/@core/components/CardAddEditDialog.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVerticalSimple: typeof import('./src/@core/components/CardStatisticsVerticalSimple.vue')['default']
    ConfirmDialog: typeof import('./src/@core/components/ConfirmDialog.vue')['default']
    CustomizerSection: typeof import('./src/@core/components/CustomizerSection.vue')['default']
    DialogCloseBtn: typeof import('./src/@core/components/DialogCloseBtn.vue')['default']
    EditAddressDialog: typeof import('./src/@core/components/EditAddressDialog.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    FormUpgradePlan: typeof import('./src/@core/components/form/FormUpgradePlan.vue')['default']
    I18n: typeof import('./src/@core/components/I18n.vue')['default']
    Notifications: typeof import('./src/@core/components/Notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shortcuts: typeof import('./src/@core/components/Shortcuts.vue')['default']
    TheCustomizer: typeof import('./src/@core/components/TheCustomizer.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UserInfoEditDialog: typeof import('./src/@core/components/UserInfoEditDialog.vue')['default']
  }
}
